Add a file option, which loads a key-value mapping from .json
jtangelder/template-html-loader pull request #12
Opened 2017-07-28 23:45 UTC by jafl

Built on top of PR #3, this adds a file option, which loads a key-value mapping from the specified .json file.

I couldn't find any other way to provide actual string data to the template processing.  Is there a better way?

2017-07-29 16:51 UTC, jafl commented
There is another way to do this:
```{ options: Object.assign(require(my_json_file), {...extra options...}) }```

However, I still think a files option is clearer.

2017-08-05 07:05 UTC, jtangelder requested changes
Thanks, some small comments and then it is good to go!

2017-08-05 07:05 UTC, jtangelder commented on index.js
> +      fs = require('fs');
could you undo this formatting?

2017-08-05 07:05 UTC, jtangelder commented on index.js
> +  const callback = this.async();
leave this to var, unrelated code change.

2017-08-05 07:05 UTC, jtangelder commented on index.js
> +      opt = Object.assign(JSON.parse(fs.readFileSync(file)), opt);    // ensure that opt takes precedence
code comment above the rule please.

2018-10-23 17:05 UTC, jafl commented
I'm so sorry this took so long!  I never received the email from github. with your feedback.

2022-04-20 19:06 UTC, jafl commented
Just pinging to see if it can be merged.

2022-04-26 11:18 UTC, merged

2022-04-26 11:18 UTC, jtangelder commented
Thank you John, LGTM.